# Generated by Django 4.1.1 on 2022-09-08 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(blank=True, max_length=500, null=True)),
                ("created_date_time", models.DateTimeField(auto_now_add=True)),
                ("updated_date_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("created_date_time", models.DateTimeField(auto_now_add=True)),
                ("updated_date_time", models.DateTimeField()),
                ("is_pending", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_item",
                        to="todo.carditem",
                    ),
                ),
            ],
        ),
    ]
