# Generated by Django 4.1.1 on 2022-09-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("todo", "0002_alter_carditem_updated_date_time")]

    operations = [
        migrations.AlterField(
            model_name="taskitem",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_item",
                to="todo.carditem",
            ),
        ),
        migrations.AlterField(
            model_name="taskitem",
            name="updated_date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
